import crypto from 'node:crypto';

export function wait(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

export async function maintainAsyncJob(jobExecuter: () => Promise<void>, restartDelay: number) {
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  while (true) {
    try {
      await jobExecuter();
    } catch (e) {
      console.log(e);
      console.log('Job restarting !!!');
    } finally {
      await wait(restartDelay);
    }
  }
}

export function uuid() {
  return crypto.randomUUID();
}

/**
 * Extracts the creation timestamp from a 63-bit ID generated by the database's
 * `generate_id()` function. Layout: 42-bit ms timestamp | 21-bit random.
 */
export function dateFromId(id: bigint | string): Date {
  const big = typeof id === 'bigint' ? id : BigInt(id);
  const ms = big >> 21n;
  return new Date(Number(ms));
}
